application: nimbusly-diceroller
version: 1
runtime: python
api_version: 1

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /javascript
  static_dir: javascript

- url: /
  static_files: odds.html
  upload: odds.html

- url: /test
  static_dir: test

- url: .*
  script: main.py

