application: nimbusly-diceroller
version: 1
runtime: python
api_version: 1

handlers:
- url: /cache.manifest
  static_files: cache.manifest
  mime_type: text/cache-manifest
  upload: cache.manifest
  expiration: 1s
  
- url: /stylesheets
  static_dir: stylesheets

- url: /javascript
  static_dir: javascript

- url: /images
  static_dir: images

- url: /
  static_files: mobile_roller.html
  upload: mobile_roller.html

- url: /(.*\.html)
  static_files: \1
  upload: .*\.html

- url: /test
  static_dir: test

- url: .*
  script: main.py


